######################################################################
# Automatically generated by qmake (3.0) Wed Nov 15 12:15:08 2017
######################################################################

TEMPLATE = app
TARGET = GraphicsTest
INCLUDEPATH += .
CONFIG += c++11
QT += widgets


# Input
HEADERS += include/EventItem.h include/GraphicsView.h
SOURCES += main.cpp src/EventItem.cpp
