######################################################################
# Automatically generated by qmake (3.0) Thu Nov 16 09:07:11 2017
######################################################################

TEMPLATE = app
TARGET = GraphicsTest
INCLUDEPATH += .
CONFIG += c++11
QT += widgets

# Input
HEADERS += include/Arrow.h include/EventItem.h include/GraphicsView.h
SOURCES += main.cpp src/Arrow.cpp src/EventItem.cpp src/GraphicsView.cpp
