######################################################################
# Automatically generated by qmake (3.0) Wed Nov 15 17:51:32 2017
######################################################################

TEMPLATE = app
TARGET = GraphicsTest
INCLUDEPATH += .
QT += widgets
CONFIG += c++11

# Input
HEADERS += include/Arrow.h include/EventItem.h include/GraphicsView.h
SOURCES += main.cpp src/Arrow.cpp src/EventItem.cpp
